baseURL = "https://coronamex.github.io"
languageCode = "es-mx"
theme = "raditian"
relativeURLs = true
# uglyURLs = true

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Mundo"
  URL = "/mundo"
  weight = 2

  [[menu.header]]
  name = "Casos"
  URL = "/casos"
  weight = 3

  [[menu.header]]
  name = "Estados"
  URL = "/estados"
  weight = 4

  [[menu.header]]
  name = "Municipios"
  URL = "/municipios"
  weight = 5

  [[menu.header]]
  name = "Clínicos"
  URL = "/clinicos"
  weight = 6

  [[menu.header]]
  name = "Muertes"
  URL = "/muertes"
  weight = 7

  [[menu.header]]
  name = "Socioeconómicos"
  URL = "/socioeconomicos"
  weight = 8

  [[menu.footer]]
  name = "Mundo"
  URL = "/mundo"
  weight = 2

  [[menu.footer]]
  name = "Casos"
  URL = "/casos"
  weight = 3

  [[menu.footer]]
  name = "Estados"
  URL = "/estados"
  weight = 4

  [[menu.footer]]
  name = "Municipios"
  URL = "/municipios"
  weight = 5

  [[menu.footer]]
  name = "Clínicos"
  URL = "/clinicos"
  weight = 6

  [[menu.footer]]
  name = "Muertes"
  URL = "/muertes"
  weight = 7

  [[menu.footer]]
  name = "Socioeconómicos"
  URL = "/socioeconomicos"
  weight = 8


[params]
  copyright = "Copyright © Sur Herrera Paredes. CC BY-NC 4."
  logo = "imagenes/logo1.png"
  logo_2x = "imagenes/logo1.png"
  logo_alt = "CoronaMex"

[taxonomies]
  etiqueta = "etiquetas"
  seccion = "secciones"
